name: sonar scan and build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      #- name: msbuild setup
       # uses: microsoft/setup-msbuild@v2 

      - name: Build
        run: |
          msbuild ${{ github.workspace }}\CallCenterV2\CallCenterV2.sqlproj /t:Build /p:Configuration=Release
        shell: cmd
      - name: upload
        uses: actions/upload-artifact@v4.3.3
        with:
           name: NPADB
           path: ${{ github.workspace }}
